- id: sunrise_lights_off
  alias: Turn off lights before sun rises
  trigger:
  - platform: sun
    event: sunrise
    offset: +00:30:00
  action:
  - service: light.turn_off
    entity_id: group.upstairs
- id: Timerstart_master_tap
  alias: Trigger the Bamboo Timer
  trigger:
  - device_id: d146fcaff11a4a1184feb7db7b778976
    domain: switch
    entity_id: switch.relay2_2
    platform: device
    type: turned_on
  action:
  - data: {}
    data_template:
      duration: 00:{{ states.input_number.bamboo_run_time.state | int }}:00
      entity_id: timer.bamboo_tap
    entity_id: timer.bamboo_tap
    service: timer.start
- id: Timerstop_master_tap
  alias: Master Timerstop
  trigger:
  - event_data:
      entity_id: timer.master_tap
    event_type: timer.finished
    platform: event
  action:
  - device_id: d146fcaff11a4a1184feb7db7b778976
    domain: switch
    entity_id: switch.relay2_2
    type: turn_off
  - delay: '1'
  - device_id: d146fcaff11a4a1184feb7db7b778976
    domain: switch
    entity_id: switch.relay4_2
    type: turn_off
- action:
  - service: homeassistant.turn_on
    entity_id: switch.relay3_2
  alias: Turn master solenoid on for Bamboo Tap
  condition: []
  id: '1537592826761'
  trigger:
  - entity_id: switch.relay2_2
    platform: state
    to: 'on'
- action:
  - service: homeassistant.turn_on
    entity_id: switch.relay3_2
  alias: Turn master solenoid on for Citrus Tap
  condition: []
  id: '1537592826762'
  trigger:
  - entity_id: switch.relay4_2
    platform: state
    to: 'on'
- id: letsencrypt-renewal
  alias: Let's Encrypt Renewal
  trigger:
  - platform: time
    at: 00:00:00
  action:
  - service: hassio.addon_restart
    data:
      addon: core_letsencrypt
- id: '1587734953493'
  alias: Turn on new backyard tap
  description: ''
  trigger:
  - device_id: d146fcaff11a4a1184feb7db7b778976
    domain: switch
    entity_id: switch.relay2_2
    platform: device
    type: turned_on
  - device_id: d146fcaff11a4a1184feb7db7b778976
    domain: switch
    entity_id: switch.relay4_2
    platform: device
    type: turned_on
  condition:
  - condition: device
    device_id: d146fcaff11a4a1184feb7db7b778976
    domain: switch
    entity_id: switch.backyard_tap
    type: is_off
  action:
  - delay: '1'
  - device_id: d146fcaff11a4a1184feb7db7b778976
    domain: switch
    entity_id: switch.relay3_2
    type: turn_on
  - delay: '2'
  - device_id: d146fcaff11a4a1184feb7db7b778976
    domain: switch
    entity_id: switch.backyard_tap
    type: turn_on
- id: '1587735321441'
  alias: Turn off new backyard tap
  description: ''
  trigger:
  - device_id: d146fcaff11a4a1184feb7db7b778976
    domain: switch
    entity_id: switch.relay4_2
    platform: device
    type: turned_off
  - device_id: d146fcaff11a4a1184feb7db7b778976
    domain: switch
    entity_id: switch.relay2_2
    platform: device
    type: turned_off
  condition:
  - condition: device
    device_id: d146fcaff11a4a1184feb7db7b778976
    domain: switch
    entity_id: switch.relay2_2
    type: is_off
  - condition: device
    device_id: d146fcaff11a4a1184feb7db7b778976
    domain: switch
    entity_id: switch.relay4_2
    type: is_off
  action:
  - delay: '2'
  - device_id: d146fcaff11a4a1184feb7db7b778976
    domain: switch
    entity_id: switch.backyard_tap
    type: turn_off
  - delay: '2'
  - device_id: d146fcaff11a4a1184feb7db7b778976
    domain: switch
    entity_id: switch.relay3_2
    type: turn_off
- id: '1587912758871'
  alias: Weekly Bamboo Watering
  description: Turn on the bamboo tap when the sun rises
  trigger:
  - event: sunrise
    platform: sun
  condition:
  - after: 00:00:00
    before: '23:59:59'
    condition: time
    weekday:
    - sat
  - above: '48'
    condition: numeric_state
    entity_id: sensor.hours_of_no_rain_in_last_3_days
  - below: '5'
    condition: numeric_state
    entity_id: sensor.bom_rain_today
  action:
  - device_id: d146fcaff11a4a1184feb7db7b778976
    domain: switch
    entity_id: switch.relay2_2
    type: turn_on
  - delay: 00:10:00
  - device_id: d146fcaff11a4a1184feb7db7b778976
    domain: switch
    entity_id: switch.relay2_2
    type: turn_off
- id: '1587948287507'
  alias: Trigger Vegepod Timer
  description: Start the timer to automatically turn off the Vegepod tap after a period
  trigger:
  - device_id: d146fcaff11a4a1184feb7db7b778976
    domain: switch
    entity_id: switch.relay4_2
    platform: device
    type: turned_on
  condition: []
  action:
  - data: {}
    data_template:
      duration: 00:{{ states.input_number.vegepod_run_time.state | int }}:00
      entity_id: timer.vegepod_tap
    entity_id: timer.vegepod_tap
    service: timer.start
- id: '1587949237228'
  alias: Vegepod timer finished
  description: ''
  trigger:
  - event_data:
      entity_id: timer.vegepod_tap
    event_type: timer.finished
    platform: event
  condition: []
  action:
  - device_id: d146fcaff11a4a1184feb7db7b778976
    domain: switch
    entity_id: switch.relay4_2
    type: turn_off
- id: '1588575129221'
  alias: Turn on the Front Master tap
  description: Turn on the main tap when a solenoid gets turned on.
  trigger:
  - device_id: 61d75c74ebc24cd18540c73168a38d17
    domain: switch
    entity_id: switch.relay5
    platform: device
    type: turned_on
  - device_id: 61d75c74ebc24cd18540c73168a38d17
    domain: switch
    entity_id: switch.relay6
    platform: device
    type: turned_on
  condition: []
  action:
  - delay: '2'
  - device_id: 61d75c74ebc24cd18540c73168a38d17
    domain: switch
    entity_id: switch.front_garden_tap
    type: turn_on
- id: '1588575426923'
  alias: Turn off the Front Master tap
  description: Turn off the main tap when all the solenoids are off.
  trigger:
  - device_id: 61d75c74ebc24cd18540c73168a38d17
    domain: switch
    entity_id: switch.relay5
    platform: device
    type: turned_off
  - device_id: 61d75c74ebc24cd18540c73168a38d17
    domain: switch
    entity_id: switch.relay6
    platform: device
    type: turned_off
  condition:
  - condition: device
    device_id: 61d75c74ebc24cd18540c73168a38d17
    domain: switch
    entity_id: switch.relay5
    type: is_off
  - condition: device
    device_id: 61d75c74ebc24cd18540c73168a38d17
    domain: switch
    entity_id: switch.relay6
    type: is_off
  action:
  - delay: '1'
  - device_id: 61d75c74ebc24cd18540c73168a38d17
    domain: switch
    entity_id: switch.front_garden_tap
    type: turn_off
- id: '1588576798684'
  alias: Bi-daily water the Front Garden
  description: Water the front vegepod and plants about twice daily at sunrise for
    5 mins
  trigger:
  - event: sunrise
    offset: 00:10:00
    platform: sun
  condition:
  - after: 00:00:00
    before: '23:59:59'
    condition: time
    weekday:
    - sun
    - tue
    - thu
  - above: '48'
    condition: numeric_state
    entity_id: sensor.hours_of_no_rain_in_last_3_days
  - below: '5'
    condition: numeric_state
    entity_id: sensor.bom_rain_today
  action:
  - device_id: 61d75c74ebc24cd18540c73168a38d17
    domain: switch
    entity_id: switch.relay5
    type: turn_on
  - delay: '300'
  - device_id: 61d75c74ebc24cd18540c73168a38d17
    domain: switch
    entity_id: switch.front_garden_tap
    type: turn_off
  - delay: '5'
  - device_id: 61d75c74ebc24cd18540c73168a38d17
    domain: switch
    entity_id: switch.relay5
    type: turn_off
