- id: sunrise_lights_off
  alias: Turn off lights before sun rises
  trigger:
  - platform: sun
    event: sunrise
    offset: +00:30:00
  action:
  - service: light.turn_off
    entity_id: group.upstairs
- action:
  - data: {}
    entity_id: switch.irrigation_relay_5
    service: homeassistant.turn_on
  alias: 'Irrigation: Relay 5 Daily start (Front Garden)'
  condition:
  - above: '40'
    condition: numeric_state
    entity_id: sensor.hours_of_no_rain_in_last_3_days
  - below: '2'
    condition: numeric_state
    entity_id: sensor.bom_rain_today
  id: '1505475104246'
  trigger:
  - at: '19:01:00'
    platform: time
- action:
  - service: timer.start
    data_template:
      entity_id: timer.front_garden
      duration: 00:{{ states.input_number.front_garden_run_time.state | int }}:00
  alias: Turn Front Garden Irrigation On
  id: Timerstart_frontgarden
  trigger:
    platform: state
    entity_id: switch.irrigation_relay_5
    to: 'on'
- action:
  - service: homeassistant.turn_off
    data:
      entity_id: switch.irrigation_relay_5
  alias: Front Garden Timerstop
  id: Timerstop_frontgarden
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.front_garden
- action:
  - service: timer.start
    data_template:
      entity_id: timer.carport_tap
      duration: 00:{{ states.input_number.carport_tap_run_time.state | int }}:00
  alias: Turn Carport Garden Irrigation On
  id: Timerstart_carport_garden
  trigger:
    platform: state
    entity_id: switch.irrigation_relay_6
    to: 'on'
- action:
  - service: homeassistant.turn_off
    data:
      entity_id: switch.irrigation_relay_6
  alias: Carport Garden Timerstop
  id: Timerstop_carport_garden
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.carport_tap
- action:
  - service: timer.start
    data_template:
      entity_id: timer.master_tap
      duration: 00:{{ states.input_number.master_tap_run_time.state | int }}:00
  alias: Turn Master Irrigation On
  id: Timerstart_master_tap
  trigger:
    platform: state
    entity_id: switch.relay3_2
    to: 'on'
- action:
  - service: homeassistant.turn_off
    data:
      entity_id: switch.relay3_2
  alias: Master Timerstop
  id: Timerstop_master_tap
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.master_tap
- action:
  - service: homeassistant.turn_on
    entity_id: switch.relay3_2
  alias: Turn master solenoid on for Bamboo Tap
  condition: []
  id: '1537592826761'
  trigger:
  - entity_id: switch.relay2_2
    platform: state
    to: 'on'
- action:
  - service: homeassistant.turn_on
    entity_id: switch.relay3_2
  alias: Turn master solenoid on for Citrus Tap
  condition: []
  id: '1537592826762'
  trigger:
  - entity_id: switch.relay4_2
    platform: state
    to: 'on'
- id: letsencrypt-renewal
  alias: Let's Encrypt Renewal
  trigger:
  - platform: time
    at: 00:00:00
  action:
  - service: hassio.addon_restart
    data:
      addon: core_letsencrypt
- id: '1587734953493'
  alias: Turn on new backyard tap
  description: ''
  trigger:
  - device_id: d146fcaff11a4a1184feb7db7b778976
    domain: switch
    entity_id: switch.relay2_2
    platform: device
    type: turned_on
  - device_id: d146fcaff11a4a1184feb7db7b778976
    domain: switch
    entity_id: switch.relay4_2
    platform: device
    type: turned_on
  condition:
  - condition: device
    device_id: d146fcaff11a4a1184feb7db7b778976
    domain: switch
    entity_id: switch.backyard_tap
    type: is_off
  action:
  - delay: '1'
  - device_id: d146fcaff11a4a1184feb7db7b778976
    domain: switch
    entity_id: switch.relay3_2
    type: turn_on
  - delay: '2'
  - device_id: d146fcaff11a4a1184feb7db7b778976
    domain: switch
    entity_id: switch.backyard_tap
    type: turn_on
- id: '1587735321441'
  alias: Turn off new backyard tap
  description: ''
  trigger:
  - device_id: d146fcaff11a4a1184feb7db7b778976
    domain: switch
    entity_id: switch.relay4_2
    platform: device
    type: turned_off
  - device_id: d146fcaff11a4a1184feb7db7b778976
    domain: switch
    entity_id: switch.relay2_2
    platform: device
    type: turned_off
  condition:
  - condition: device
    device_id: d146fcaff11a4a1184feb7db7b778976
    domain: switch
    entity_id: switch.relay2_2
    type: is_off
  - condition: device
    device_id: d146fcaff11a4a1184feb7db7b778976
    domain: switch
    entity_id: switch.relay4_2
    type: is_off
  action:
  - delay: '2'
  - device_id: d146fcaff11a4a1184feb7db7b778976
    domain: switch
    entity_id: switch.backyard_tap
    type: turn_off
  - delay: '2'
  - device_id: d146fcaff11a4a1184feb7db7b778976
    domain: switch
    entity_id: switch.relay3_2
    type: turn_off
